name: CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:
  push :
    branches :
      - main

concurrency:
  group: ci-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  dependency-guard:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: dependency-guard
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: dependencyGuardBaseline
          check-task: dependencyGuard

  ktlint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: ktlint
        uses: ./.github/actions/gradle-task-with-commit
        with:
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fix-task: ktlintFormat
          check-task: ktlintCheck

  detekt:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: detekt
        uses: ./.github/actions/gradle-task
        with:
          arguments: detektAll
          write-cache-key: main-build-artifacts

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu, windows ]
    runs-on: ${{ matrix.runner }}-latest
    steps:
      - name: check out
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: unit tests
        uses: ./.github/actions/gradle-task
        with:
          task: test
          write-cache-key: main-build-artifacts

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: ${{ github.workspace }}/**/build/reports/tests/

      - name: Unit test results
        uses: mikepenz/action-junit-report@v3
        if: failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/**/TEST-*.xml'
          check_name: Unit Test Results - ${{runner.os}}

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - dependency-guard
      - detekt
      - ktlint
      - unit-tests
    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
